name: Android CI with Unit Tests, Secrets, and Signed Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure Secrets and Keystore
        env:
          API_KEY: ${{ secrets.APIKEY }}
          BASE_URL: ${{ secrets.BASEURL }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "--- Setting up API Keys and Base URL ---"
          echo "APIKEY=$API_KEY" >> $GITHUB_ENV
          echo "BASEURL=$BASE_URL" >> $GITHUB_ENV
          echo "--- Configuring Keystore for Signing ---"
          mkdir -p "$HOME/.android"
          KEYSTORE_FILE="$HOME/.android/release.jks"
          echo $KEYSTORE_BASE64 | base64 --decode > "$KEYSTORE_FILE"

          echo "KEYSTORE_PATH=$KEYSTORE_FILE" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> $GITHUB_ENV
          echo "KEY_ALIAS=$KEY_ALIAS" >> $GITHUB_ENV
          echo "KEY_PASSWORD=$KEY_PASSWORD" >> $GITHUB_ENV

          echo "Secrets and keystore configured."

#      - name: Run Unit Tests for Domain Module
#        run: ./gradlew :domain:testDebugUnitTest --info

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Build Release AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload Domain Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: domain-unit-test-report
          path: domain/build/reports/tests/testDebugUnitTest/

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab
